/**
 * `slopweaver init`'s work-console bootstrap step.
 *
 * Run once at first install. Idempotent — re-running does nothing
 * destructive. Three responsibilities:
 *
 *   1. Create the `ai-work-console` git branch (default name; configurable)
 *      if the cwd is a git repo and the branch doesn't exist yet.
 *   2. Scaffold the `.claude/personal/` directory structure with empty
 *      placeholder markdown files (the layout that `get_work_console_state`
 *      expects). Existing files are never overwritten.
 *   3. Drop a memory file at `.claude/SLOPWEAVER-MEMORY.md` and ensure
 *      `<repo>/CLAUDE.md` imports it so future Claude Code sessions
 *      automatically know to stay on the work-console branch when running
 *      slopweaver slash commands.
 *
 * All filesystem operations go through the `gitRunner` and `writers`
 * injection points so tests can pass fakes. Real implementations are wired
 * up in `apps/mcp-local/src/init/bootstrap-work-console-runtime.ts`.
 */

import { ResultAsync, errAsync, okAsync } from '@slopweaver/errors';
import type { BaseError } from '@slopweaver/errors';
import { ensureWorkConsoleBranch, type GitRunner } from './branch.ts';
import { DEFAULT_WORK_CONSOLE_BRANCH, resolveWorkConsoleConfig } from './config.ts';

const DEFAULT_CONSOLE_REL_DIR = '.claude/personal';
const SLOPWEAVER_MEMORY_REL_PATH = '.claude/SLOPWEAVER-MEMORY.md';
// Memory import lives under `.claude/CLAUDE.md` rather than root `CLAUDE.md`
// so the bootstrap never modifies a tracked root file. Claude Code reads
// both locations and the `.claude/` directory is conventionally gitignored
// (see .gitignore in the slopweaver public repo for the canonical entry).
// This is the difference between a smooth dogfood loop and accidentally
// staging a one-line tracked-file edit on every bootstrap.
const PROJECT_CLAUDE_MD_REL_PATH = '.claude/CLAUDE.md';

const SLOPWEAVER_MEMORY_CONTENT = `# SlopWeaver work console rules

> Generated by SlopWeaver (via either \`slopweaver init\` or the
> \`bootstrap_work_console\` MCP tool that \`/session-start\` runs on
> first use). Edit freely — the slopweaver MCP tools will respect any
> rules you add. See the docs at
> <https://github.com/slopweaver/slopweaver> for the rationale.

## Branch convention

The AI work console lives on a dedicated git branch (default name:
\`ai-work-console\`). The following slopweaver slash commands MUST run on
that branch — never on a feature / PR branch:

- \`/session-start\` (and \`/mcp__slopweaver__session-start\`)
- \`/lock-in\`
- \`/reconcile\`
- \`/fan-out-audit\`
- \`/style-rule\`, \`/style-edit\`, \`/correct\`

Each of those prompts calls the \`ensure_work_console_branch\` MCP tool as
its first step. If you find yourself on a feature branch when starting one
of these flows, **let the tool switch the branch for you**. Don't bypass
it.

PR work happens on separate worktree branches as usual. The work console
branch is for context, drafts, deltas, and decision logs — not code
shipping to production.

## Layout (under \`.claude/personal/\`)

- \`contexts/\` — durable identity, priorities, team directory
- \`work/\` — active work files (one per programme)
- \`state/\` — generated delta files + walk-feedback JSONL
- \`rules/\` — voice + style + workflow rules
- \`daily/\` — daily journals (YYYY-MM/DD.md)
- \`drafts/\` — drafted messages (file-first, never sent direct)
- \`handoffs/\` — handoff prompts for parallel CMUX chats
- \`HANDOVER-FOR-AI-AGENTS.md\` — top-level operating doc

## Editing

Edit any of these files freely. The slopweaver MCP tools (\`read_console_file\`,
\`write_console_file\`, \`list_console_files\`) operate on the same tree.
Re-run \`/session-start\` after manual edits to refresh the snapshot.
`;

type WriteResult = {
  bytesWritten: number;
  created: boolean;
};

type Writers = {
  readonly fileExists: (absPath: string) => Promise<boolean>;
  readonly readFile: (absPath: string) => Promise<string | null>;
  readonly writeFile: (absPath: string, content: string) => Promise<WriteResult>;
  readonly mkdir: (absPath: string) => Promise<void>;
};

export type BootstrapBranchAction = 'no_git_repo' | 'already_on_branch' | 'switched' | 'created_and_switched';

export type BootstrapResult = {
  branch: string;
  branchAction: BootstrapBranchAction;
  consoleDir: string;
  filesCreated: ReadonlyArray<string>;
  memoryFileCreated: boolean;
  claudeMdImportAdded: boolean;
  /** Relative paths of slash-command shims created under .claude/commands/. */
  slashCommandsCreated: ReadonlyArray<string>;
};

/**
 * Slash-command shims. Each entry produces a `<repo>/.claude/commands/<name>.md`
 * file whose body tells Claude Code to invoke the corresponding MCP prompt
 * under the SlopWeaver server. After this, the user's slash-command menu
 * shows the bare `/session-start` form instead of the qualified
 * `/mcp__slopweaver__session-start`.
 *
 * Keep the body minimal: a one-line description + an instruction to run
 * the underlying prompt. The MCP prompt itself carries the substantive
 * orchestration.
 */
const SLASH_COMMAND_SHIMS: ReadonlyArray<{ name: string; description: string }> = [
  { name: 'session-start', description: 'Refresh the AI work console: branch check → fan-out → reconcile → snapshot.' },
  {
    name: 'fan-out-audit',
    description: 'First-run deep backfill of the work console from every connected MCP server.',
  },
  { name: 'lock-in', description: 'Walk the ranked queue one item at a time. Push-style execution.' },
  { name: 'reconcile', description: 'Cross-reference work-file open items against the latest deltas.' },
  { name: 'style-rule', description: 'Capture a voice / style / workflow rule. Verbatim.' },
  { name: 'style-edit', description: 'Amend or remove an existing rule.' },
  { name: 'correct', description: 'Capture a user pushback as high-signal training data.' },
  {
    name: 'calibration-report',
    description: 'Show /lock-in acceptance / edit / rejection rates and top friction tags.',
  },
  { name: 'recompile-profile', description: 'Refresh contexts/core-profile.md from latest signal across MCP servers.' },
  { name: 'decided', description: "Append a decision to the matching work file's Key decisions section." },
  { name: 'focus', description: 'Set the focus scope for this session. Subsequent snapshots filter accordingly.' },
];

const SLASH_COMMAND_REL_DIR = '.claude/commands';

function renderSlashCommandShim(name: string, description: string): string {
  return `---
description: ${description}
---

Fetch and run the SlopWeaver MCP server's \`${name}\` prompt now. Use
the MCP \`prompts/get\` request with \`name: "${name}"\` against the
\`slopweaver\` server, and follow the returned prompt body exactly.

Forward any arguments the user typed after \`/${name}\` to the MCP
prompt's argument map (see its argument schema). When there are no
arguments, send an empty arguments object.

Equivalent invocation: \`/mcp__slopweaver__${name}\`. This shim exists
so the bare \`/${name}\` name appears in the slash-command menu.
`;
}

interface BootstrapWorkConsoleFailedError extends BaseError {
  readonly code: 'BOOTSTRAP_WORK_CONSOLE_FAILED';
  readonly detail: string;
}

const failed = (detail: string): BootstrapWorkConsoleFailedError => ({
  code: 'BOOTSTRAP_WORK_CONSOLE_FAILED',
  message: `Work-console bootstrap failed: ${detail}`,
  detail,
});

export type RunBootstrapArgs = {
  cwd: string;
  /** Override the branch name. Defaults to `ai-work-console`. */
  branch?: string;
  /** Inject for tests. Defaults to the real spawn-based runner. */
  gitRunner?: GitRunner;
  writers: Writers;
  /**
   * Whether to allow stashing uncommitted changes when switching branches.
   * Defaults to false — the wizard prompts the user before stashing.
   */
  allowSwitchWithUncommitted?: boolean;
};

/**
 * Scaffold layout. Every entry is a markdown file we create EMPTY-ish (with
 * a one-line header) if it doesn't already exist. Directories are implied
 * by file parents.
 */
const SCAFFOLD_FILES: ReadonlyArray<{ relPath: string; seedContent: string }> = [
  {
    relPath: 'contexts/identities.md',
    seedContent: `# Identities

Resolve via \`/fan-out-audit\`. SlopWeaver writes this file from your
connected MCP servers (GitHub, Slack, Linear, Gmail, etc.).

| Platform | Identifier | Notes |
| --- | --- | --- |
`,
  },
  {
    relPath: 'contexts/team-directory.md',
    seedContent: `# Team directory

The people you actually interact with. SlopWeaver populates this from
your MCP servers in \`/fan-out-audit\`. Edit freely.
`,
  },
  {
    relPath: 'contexts/core-profile.md',
    seedContent: `---
name: core-profile
description: ALWAYS-LOADED profile. Read first every session.
metadata:
  type: profile
---

# Profile at a glance

Run \`/fan-out-audit\` to populate this file from your MCP servers.

## Identity

_TBD — populated by /fan-out-audit_

## Current priorities (ranked, YYYY-MM-DD)

_TBD_

## Voice

See [communication-style.md](../rules/communication-style.md).

## Open loops

_TBD_
`,
  },
  {
    relPath: 'rules/communication-style.md',
    seedContent: `# Communication style

Voice rules captured via \`/style-rule\` and \`/style-edit\`. SlopWeaver
applies these to every draft.

## Defaults (override via /style-rule)

- No em-dashes; use a comma or two sentences instead.
- No exclamation marks.
- Honest hedges (\`I think\`, \`probably\`) over false confidence.
- Direct subject + verb. Plain English.
`,
  },
  {
    relPath: 'rules/development-workflow.md',
    seedContent: `# Development workflow

Workflow conventions captured via \`/style-rule\` (category:
development-workflow). Populated by \`/fan-out-audit\` from observed PRs.
`,
  },
  {
    relPath: 'rules/ai-tropes.md',
    seedContent: `# AI tropes to avoid

Patterns the user has flagged as "sounds like AI". Captured via
\`/correct\` and \`/style-rule\`.
`,
  },
  {
    relPath: 'state/.gitkeep',
    seedContent: '',
  },
  {
    relPath: 'work/.gitkeep',
    seedContent: '',
  },
  {
    relPath: 'daily/.gitkeep',
    seedContent: '',
  },
  {
    relPath: 'drafts/.gitkeep',
    seedContent: '',
  },
  {
    relPath: 'handoffs/.gitkeep',
    seedContent: '',
  },
  {
    relPath: 'HANDOVER-FOR-AI-AGENTS.md',
    seedContent: `# Handover for AI agents

Top-level operating doc for any AI agent (Claude Code, Cursor, Cline,
etc.) that picks up work in this repo. SlopWeaver populates the
substance via \`/fan-out-audit\` and ongoing edits.

## Rules

1. Always start with \`/session-start\`.
2. SlopWeaver slash commands run on the \`ai-work-console\` branch.
   PR work runs on feature branches.
3. Never auto-send messages. Draft to disk under \`drafts/\`; the user
   sends.
4. Apply the rules under \`rules/\` to every draft.

## What's here

See the README at the repo root, plus [contexts/core-profile.md](./contexts/core-profile.md)
for the operator's fingerprint.
`,
  },
];

export function runBootstrapWorkConsole(
  args: RunBootstrapArgs,
): ResultAsync<BootstrapResult, BootstrapWorkConsoleFailedError> {
  const branch = args.branch ?? DEFAULT_WORK_CONSOLE_BRANCH;
  const config = resolveWorkConsoleConfig({
    cwd: args.cwd,
    branch,
  });
  const branchPromise = ensureWorkConsoleBranch({
    config,
    ...(args.gitRunner !== undefined && { runner: args.gitRunner }),
    allowSwitchWithUncommitted: args.allowSwitchWithUncommitted ?? false,
  });
  return branchPromise
    .mapErr<BootstrapWorkConsoleFailedError>((e) => failed(e.message))
    .andThen((branchResult) => {
      const branchAction: BootstrapBranchAction = branchResult.action;
      const consoleDir = `${config.cwd}/${DEFAULT_CONSOLE_REL_DIR}`;
      return runScaffold({ consoleDir, writers: args.writers }).andThen((filesCreated) =>
        runMemoryFile({ cwd: config.cwd, writers: args.writers }).andThen((memoryOutcome) =>
          runSlashCommands({ cwd: config.cwd, writers: args.writers }).map((slashCommandsCreated) => ({
            branch,
            branchAction,
            consoleDir,
            filesCreated,
            memoryFileCreated: memoryOutcome.memoryFileCreated,
            claudeMdImportAdded: memoryOutcome.claudeMdImportAdded,
            slashCommandsCreated,
          })),
        ),
      );
    });
}

function runSlashCommands(args: {
  cwd: string;
  writers: Writers;
}): ResultAsync<ReadonlyArray<string>, BootstrapWorkConsoleFailedError> {
  const promises = SLASH_COMMAND_SHIMS.map(async (shim): Promise<string | null> => {
    const relPath = `${SLASH_COMMAND_REL_DIR}/${shim.name}.md`;
    const absPath = `${args.cwd}/${relPath}`;
    const exists = await args.writers.fileExists(absPath);
    if (exists) return null;
    await args.writers.writeFile(absPath, renderSlashCommandShim(shim.name, shim.description));
    return relPath;
  });
  return wrapAll(promises);
}

function runScaffold(args: {
  consoleDir: string;
  writers: Writers;
}): ResultAsync<ReadonlyArray<string>, BootstrapWorkConsoleFailedError> {
  const promises = SCAFFOLD_FILES.map(async (entry): Promise<string | null> => {
    const absPath = `${args.consoleDir}/${entry.relPath}`;
    const exists = await args.writers.fileExists(absPath);
    if (exists) return null;
    await args.writers.writeFile(absPath, entry.seedContent);
    return entry.relPath;
  });
  return wrapAll(promises);
}

function runMemoryFile(args: {
  cwd: string;
  writers: Writers;
}): ResultAsync<{ memoryFileCreated: boolean; claudeMdImportAdded: boolean }, BootstrapWorkConsoleFailedError> {
  const memoryAbs = `${args.cwd}/${SLOPWEAVER_MEMORY_REL_PATH}`;
  const claudeMdAbs = `${args.cwd}/${PROJECT_CLAUDE_MD_REL_PATH}`;
  const importLine = `@${SLOPWEAVER_MEMORY_REL_PATH}`;
  const importStanza = `\n${importLine}\n`;

  const memoryPromise = (async (): Promise<boolean> => {
    const exists = await args.writers.fileExists(memoryAbs);
    if (exists) return false;
    await args.writers.writeFile(memoryAbs, SLOPWEAVER_MEMORY_CONTENT);
    return true;
  })();

  const claudeMdPromise = (async (): Promise<boolean> => {
    const existing = await args.writers.readFile(claudeMdAbs);
    if (existing === null) {
      const seed = `# Claude Code memory\n${importStanza}`;
      await args.writers.writeFile(claudeMdAbs, seed);
      return true;
    }
    if (existing.includes(importLine)) {
      return false;
    }
    const next = existing.endsWith('\n') ? `${existing}${importStanza}` : `${existing}\n${importStanza}`;
    await args.writers.writeFile(claudeMdAbs, next);
    return true;
  })();

  return ResultAsync.fromPromise<
    { memoryFileCreated: boolean; claudeMdImportAdded: boolean },
    BootstrapWorkConsoleFailedError
  >(
    Promise.all([memoryPromise, claudeMdPromise]).then(([memoryFileCreated, claudeMdImportAdded]) => ({
      memoryFileCreated,
      claudeMdImportAdded,
    })),
    (e) => failed(e instanceof Error ? e.message : String(e)),
  );
}

function wrapAll<T>(
  promises: ReadonlyArray<Promise<T | null>>,
): ResultAsync<ReadonlyArray<T>, BootstrapWorkConsoleFailedError> {
  return ResultAsync.fromPromise<ReadonlyArray<T | null>, BootstrapWorkConsoleFailedError>(Promise.all(promises), (e) =>
    failed(e instanceof Error ? e.message : String(e)),
  ).andThen<ReadonlyArray<T>, BootstrapWorkConsoleFailedError>((results) =>
    okAsync(results.filter((r): r is T => r !== null)),
  );
}

// Re-export for callers that need to handle the typed error.
export type { BootstrapWorkConsoleFailedError as InitBootstrapError };

// Public exports for the bootstrap MCP tool + docs. These were
// previously knip-stripped when the bootstrap was app-internal; now
// that it's reachable from `@slopweaver/mcp-server` they're part of
// the public surface.
export const SCAFFOLD_FILE_LIST = SCAFFOLD_FILES.map((f) => f.relPath);
export const slopweaverMemoryContent = SLOPWEAVER_MEMORY_CONTENT;
export const slopweaverMemoryRelPath = SLOPWEAVER_MEMORY_REL_PATH;
export const projectClaudeMdRelPath = PROJECT_CLAUDE_MD_REL_PATH;

// errAsync is reserved for future failure paths inside the bootstrap.
// Knip flags it if unreferenced; the `void` keeps the import alive
// without an extra public symbol to maintain.
void errAsync;
