/**
 * Pure builder for the `saveTransactionsFanout` request body that
 * creates a new image block on a page and links the uploaded file.
 *
 * The shape mirrors what Notion's own web client sends. Critical
 * field: `file_ids: [<uuid>]` on the block-update args — without it,
 * the block renders the broken-image SVG even though the upload
 * succeeded.
 */

export type BuildSaveTransactionsBodyArgs = {
  readonly pageId: string;
  readonly spaceId: string;
  readonly attachmentUrl: string;
  readonly fileUuid: string;
  /** New block UUID generated by the caller (UUID v4). */
  readonly newBlockId: string;
  /** Unique request id (UUID v4). Lets Notion dedupe retries. */
  readonly requestId: string;
  /** Unique transaction id (UUID v4). */
  readonly transactionId: string;
  /** Epoch ms timestamp. Stamped on the new block's created/last_edited fields. */
  readonly nowMs: number;
};

export type SaveTransactionsBody = {
  readonly requestId: string;
  readonly transactions: ReadonlyArray<{
    readonly id: string;
    readonly spaceId: string;
    readonly debug: { readonly userAction: string };
    readonly operations: ReadonlyArray<Record<string, unknown>>;
  }>;
};

export function buildSaveTransactionsBody(args: BuildSaveTransactionsBodyArgs): SaveTransactionsBody {
  return {
    requestId: args.requestId,
    transactions: [
      {
        id: args.transactionId,
        spaceId: args.spaceId,
        debug: { userAction: 'slopweaver-notion-upload' },
        operations: [
          {
            pointer: { table: 'block', id: args.newBlockId, spaceId: args.spaceId },
            path: [],
            command: 'update',
            args: {
              id: args.newBlockId,
              type: 'image',
              version: 1,
              alive: true,
              created_time: args.nowMs,
              last_edited_time: args.nowMs,
              parent_id: args.pageId,
              parent_table: 'block',
              space_id: args.spaceId,
              properties: { source: [[args.attachmentUrl]] },
              format: { display_source: args.attachmentUrl },
              file_ids: [args.fileUuid],
            },
          },
          {
            pointer: { table: 'block', id: args.pageId, spaceId: args.spaceId },
            path: ['content'],
            command: 'listAfter',
            args: { id: args.newBlockId },
          },
          {
            pointer: { table: 'block', id: args.pageId, spaceId: args.spaceId },
            path: ['last_edited_time'],
            command: 'set',
            args: args.nowMs,
          },
        ],
      },
    ],
  };
}
