/**
 * Annotation spec for `slopweaver annotate-image`. A spec is a JSON
 * document the caller hands in (typically generated by a model from a
 * natural-language prompt). Every shape carries explicit pixel
 * coordinates against the source image's dimensions.
 *
 * Coordinates are top-left origin. `x` grows right, `y` grows down.
 */

export type AnnotationColor = string;

export type AnnotationRect = {
  readonly type: 'rect';
  /** Top-left corner x in pixels. */
  readonly x: number;
  /** Top-left corner y in pixels. */
  readonly y: number;
  /** Box width in pixels. */
  readonly width: number;
  /** Box height in pixels. */
  readonly height: number;
  /** CSS colour (default `#ef4444`, slightly desaturated red). */
  readonly color?: AnnotationColor;
  /** Stroke width in pixels (default `4`). */
  readonly strokeWidth?: number;
};

export type AnnotationArrow = {
  readonly type: 'arrow';
  /** Arrow tail x. */
  readonly x1: number;
  /** Arrow tail y. */
  readonly y1: number;
  /** Arrow head x (the pointy end). */
  readonly x2: number;
  /** Arrow head y. */
  readonly y2: number;
  readonly color?: AnnotationColor;
  /** Line stroke width in pixels (default `4`). */
  readonly strokeWidth?: number;
  /** Arrowhead length in pixels (default `16`). */
  readonly headLength?: number;
};

export type AnnotationText = {
  readonly type: 'text';
  readonly x: number;
  readonly y: number;
  readonly text: string;
  readonly color?: AnnotationColor;
  /** Font size in pixels (default `24`). */
  readonly fontSize?: number;
  /** Background pill colour (default none). Use `#fff` to keep text readable on busy images. */
  readonly background?: AnnotationColor;
};

export type AnnotationShape = AnnotationRect | AnnotationArrow | AnnotationText;

export type AnnotationSpec = {
  readonly shapes: ReadonlyArray<AnnotationShape>;
};

export type AnnotateImageArgs = {
  /** Absolute path to the input PNG or JPEG. */
  readonly inputPath: string;
  /** Absolute path the annotated image is written to (PNG). */
  readonly outputPath: string;
  /** The annotation spec to draw. */
  readonly spec: AnnotationSpec;
};
